set(CMAKE_C_STANDARD 99)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_STANDARD 17)


file(GLOB_RECURSE C_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.c")
file(GLOB_RECURSE C_HEADERS "${CMAKE_CURRENT_SOURCE_DIR}/*.h")
set_source_files_properties(${C_SOURCES} PROPERTIES LANGUAGE C)
set_source_files_properties(${C_HEADERS} PROPERTIES LANGUAGE C)