name: build.yml
on:
  workflow_call:
    inputs:
      upload_artifacts:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            preset: linux
            shell: bash
            mingw: false
          - os: windows-latest
            preset: windows
            shell: msys2
            mingw: true

    env:
      CLIENT_DIR: ${{ github.workspace }}/Source/Client
      VCPKG_ROOT: ${{ github.workspace}}/vcpkg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get CMake
        if: matrix.os == 'ubuntu-latest'
        uses: lukka/get-cmake@latest

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            python3 \
            python3-jinja2 \
            ninja-build \
            pkg-config \
            libx11-dev \
            libltdl-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libgl1-mesa-dev \
            autoconf \
            autoconf-archive \
            automake \
            libtool

      - name: Install Modern Clang (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: egor-tensin/setup-clang@v2
        with:
          version: 21
          platform: x64

      - name: Setup MSYS2 (MinGW64)
        if: matrix.mingw
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-pkg-config
            zip
            tar

      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '84bab45d415d22042bd0b9081aea57f362da3f35'
          runVcpkgInstall: false
          vcpkgJsonGlob: ${{ env.CLIENT_DIR }}/vcpkg.json
          vcpkgConfigurationJsonGlob: ${{ env.CLIENT_DIR}}/vcpkg-configuration.json


      - name: Configure (Linux)
        if: matrix.shell == 'bash'
        uses: lukka/run-cmake@v10
        with:
            cmakeListsTxtPath: ${{ env.CLIENT_DIR }}/CMakeLists.txt
            configurePreset: linux

      - name: Configure (Windows MinGW)
        if: matrix.shell == 'msys2'
        shell: msys2 {0}
        run: |
          export VCPKG_ROOT=$(cygpath -u "$VCPKG_ROOT")
          export CLIENT_DIR=$(cygpath -u "$CLIENT_DIR")
          
          cd "$CLIENT_DIR"
          cmake --preset windows


      - name: Build
        if: matrix.shell == 'bash'
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: ${{ env.CLIENT_DIR }}/CMakeLists.txt
          buildPreset: linux

      - name: Build (Windows MinGW)
        if: matrix.shell == 'msys2'
        shell: msys2 {0}
        run: |
          export VCPKG_ROOT=$(cygpath -u "$VCPKG_ROOT")
          export CLIENT_DIR=$(cygpath -u "$CLIENT_DIR")

          cd "$CLIENT_DIR"
          cmake --build --preset windows

      - name: Rename Linux Release Artifact
        if: matrix.shell == 'bash'
        run: |
          mv "$CLIENT_DIR/build/linux/TheLastGateSDLRelease.tar.gz" \
             "$CLIENT_DIR/build/linux/TheLastGateSDLRelease-Linux64.tar.gz"

      - name: Rename Linux Release Artifact
        if: matrix.shell == 'msys2'
        shell: msys2 {0}
        run: |
          CLIENT_DIR_POSIX=$(cygpath -u "$CLIENT_DIR")
          mv "$CLIENT_DIR_POSIX/build/windows/TheLastGateSDLRelease.zip" \
             "$CLIENT_DIR_POSIX/build/windows/TheLastGateSDLRelease-Win64.zip"

      - name: Upload build artifacts
        if: inputs.upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-${{ matrix.preset }}
          path: |
            ${{ env.CLIENT_DIR }}/build/*/TheLastGateSDLRelease-*.*
